export enum ApiKeyTestCases {
  EXPECT_PLAIN_KEY_FORMAT = 'Plain key should match format rslive_v1_<48 hex>',
  EXPECT_KEY_HASH_DEFINED = 'Key hash should be defined',
  EXPECT_KEY_HASH_NOT_PLAIN = 'Key hash should not equal plain key',
  EXPECT_ACCOUNT_ID_MATCHES = 'Account ID should match input',
  EXPECT_LABEL_MATCHES = 'Label should match input',
  EXPECT_KEY_INDICATOR_FORMAT = 'Key indicator should match format rsliv...xxxxx',
  EXPECT_LABEL_TRUNCATED = 'Label should be truncated to 30 chars',
  EXPECT_HASH_LENGTH_64 = 'Key hash should be 64 chars (SHA256)',
  EXPECT_HASH_NO_RSLIVE = 'Key hash should not contain rslive prefix',
  EXPECT_VALID_KEY_NOT_NULL = 'Valid key should return ApiKey not null',
  EXPECT_VALID_KEY_HASH_MATCHES = 'Validated key hash should match created key',
  EXPECT_INVALID_KEY_NULL = 'Invalid key should return null',
  EXPECT_EXPIRED_KEY_NULL = 'Expired key should return null',
  EXPECT_FUTURE_EXPIRY_VALID = 'Key with future expiry should be valid',
  EXPECT_KEYS_FOR_ACCOUNT = 'Should return keys for account',
  EXPECT_ALL_KEYS_BELONG_TO_ACCOUNT = 'All keys should belong to account',
  EXPECT_EMPTY_FOR_NONEXISTENT = 'Should return empty array for non-existent account',
  EXPECT_REVOKE_SUCCESS = 'Revoke should return true',
  EXPECT_REVOKED_KEY_INVALID = 'Revoked key should be invalid',
  EXPECT_REVOKE_NONEXISTENT_FALSE = 'Revoke non-existent key should return false',
  EXPECT_LAST_USED_NULL_INITIALLY = 'last_used_at should be null initially',
  EXPECT_LAST_USED_UPDATED = 'last_used_at should be updated after updateLastUsed',
}
