
export enum ErrorCode {
  // External errors - user-facing or business logic errors
  EXTERNAL_NO_CREDITS = 'EXTERNAL_NO_CREDITS',
  EXTERNAL_BUFFER_OVERFLOW = 'EXTERNAL_BUFFER_OVERFLOW',
  EXTERNAL_INVALID_AUTH = 'EXTERNAL_INVALID_AUTH',

  // Internal errors
  INTERNAL_ENV_KEY_NOT_FOUND = 'INTERNAL_ENV_KEY_NOT_FOUND',
  INTERNAL_ZMQ_NOT_CONNECTED = 'INTERNAL_ZMQ_NOT_CONNECTED',
  INTERNAL_ZMQ_REQUEST_TIMEOUT = 'INTERNAL_ZMQ_REQUEST_TIMEOUT',
  INTERNAL_ZMQ_DESTROYED = 'INTERNAL_ZMQ_DESTROYED',
  INTERNAL_ZMQ_INVALID_RESPONSE = 'INTERNAL_ZMQ_INVALID_RESPONSE',
  INTERNAL_ZMQ_NO_PENDING_REQUEST = 'INTERNAL_ZMQ_NO_PENDING_REQUEST',
  INTERNAL_ZMQ_DECODE_FAILED = 'INTERNAL_ZMQ_DECODE_FAILED',
}
