export enum OrchestratorTestCases {
  CREDITS_LOADED_ON_CONNECT = 'Credits loaded from DB within 2 seconds after connect when initially null',
  CREDITS_DEDUCTED_AFTER_RESPONSE = 'Available credits reduced after full response cycle',
  NO_CREDITS_ERROR_WHEN_DEPLETED = 'NO_CREDITS error thrown when credits depleted after multiple responses',
  MESSAGES_BUFFERED_BEFORE_CONNECT = 'Messages buffered successfully when sent immediately after connect',
  BUFFER_OVERFLOW_ERROR = 'RECON_TIMED_OUT_RETRYING error when buffer limit reached',
  NEW_SESSION_SAVED = 'New session created and conv log saved when no existing session',
  EXISTING_SESSION_REPLAYED = 'Existing session loaded and replayed on connect',
  LARGE_CONV_SUMMARIZED = 'Large conversation history summarized before replay',
  SESSION_UPDATE_MERGED = 'Session update merges with existing session config',
  RECONNECT_WITH_MERGED_SESSION = 'Reconnect loads merged session with existing conv log',
  CREDITS_CHECK_AFTER_X_RESPONSES = 'Credits check triggered only after X response count threshold',
  ON_ERROR_DISCONNECTS = 'onError sets isVoiceProviderConnected to false',
  ON_CLOSE_DISCONNECTS = 'onClose sets isVoiceProviderConnected to false',
  RECONNECT_SAME_SESSION = 'Reconnect uses same accountId and sessionId',
  SEND_WHEN_CONNECTED = 'Send passes message directly without buffering when connected',
  BUFFER_ORDER_PRESERVED = 'Multiple buffered messages maintain FIFO order',
  FLUSH_BUFFER_ON_CONNECT = 'Buffered messages flushed in order on connect',
  NON_RESPONSE_DONE_IGNORED = 'onMsgReceived ignores non-response.done messages',
  MISSING_USAGE_HANDLED = 'onMsgReceived handles missing usage field gracefully',
  NEGATIVE_CREDITS_DISCONNECT = 'Disconnect triggered when credits go negative mid-session',
  NO_DUPLICATE_CREDITS_CHECK = 'Rapid scheduleCreditsCheck calls do not cause duplicate requests',
  NULL_SESSION_NO_REPLAY = 'No replay when getSessionData returns null for new session',
  REPLAY_SESSION_FORMAT = 'replaySession sends correct session.update message format'
}
